
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.fullname" . }}
  labels: {{- include "application.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
  - name: {{ .Values.service.portName }}
    targetPort: {{ .Values.service.targetPort }}
    port: {{ .Values.service.port }}
    protocol: TCP
  type: {{ .Values.service.type }}
